### ISSUE TITLE
there are some HTML character entities still not converted

### ISSUE THREAD

**Issue by K1ngst0m** [matthewhartman/urban-dictionary-lookup#1]
e.g.: `$ udefine RTFM`
![image](https://user-images.githubusercontent.com/34272057/164346559-c0bb29c0-5de5-4508-9e06-4f46161fdd6d.png)

**Comment by K1ngst0m** [comment]
and there are some texts missing
![image](https://user-images.githubusercontent.com/34272057/164582949-aec3b9ec-dfd4-449d-b415-805d72c10e2b.png)

**Comment by matthewhartman** [comment]
Nice pick up! Thanks for the PR! Merged it and bumped new version. Cheers!
